### ISSUE TITLE
Cannot compile on GHC 7.6.3

### ISSUE THREAD

**Issue by snoyberg** [BioHaskell/hPDB#2] opened 2014-08-17 15:46 UTC
```
[ 1 of 60] Compiling Bio.PDB.Util.ParFold ( Bio/PDB/Util/ParFold.hs, dist/build/Bio/PDB/Util/ParFold.o )
[ 2 of 60] Compiling Bio.PDB.Util.MissingInstances ( Bio/PDB/Util/MissingInstances.hs, dist/build/Bio/PDB/Util/MissingInstances.o )
[ 3 of 60] Compiling Bio.PDB.EventParser.FastParse ( Bio/PDB/EventParser/FastParse.hs, dist/build/Bio/PDB/EventParser/FastParse.o )
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Loading package array-0.4.0.1 ... linking ... done.
Loading package deepseq-1.3.0.1 ... linking ... done.
Loading package bytestring-0.10.0.2 ... linking ... done.
Loading package zlib-0.5.4.1 ... linking ... done.
Loading package text-1.1.1.3 ... linking ... done.
Loading package double-conversion-2.0.1.0 ... linking ... ghc: /home/ubuntu/.cabal/lib/x86_64-linux-ghc-7.6.3/double-conversion-2.0.1.0/libHSdouble-conversion-2.0.1.0.a: unknown symbol `_ZNK17double_conversion23StringToDoubleConverter12StringToIeeeIPKcEEdT_ibPi'
ghc: unable to load package `double-conversion-2.0.1.0'
Failed to install hPDB-1.2.0
cabal: Error: some packages failed to install:
hPDB-1.2.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by mgajda** [comment] 2016-06-05 06:31
Since we have a workaround option, and the issue is fixed in 7.8, I will keep it as-is.

**Closed by mgajda** 2016-06-05 06:31 UTC
